openapi: 3.0.3
info:
  title: Charger service API V1
  description: A charger service API description
  version: 0.1.0
servers:
  - url: 'https://charger-service-api.dimensiontech.nl/api/v1'
    description: Production
paths:
  /charge-sessions:
    get:
      operationId: getChargeSessions
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeSessionPage'
  /charge-sessions/{chargeSessionId}:
    get:
      operationId: getChargeSession
      parameters:
        - name: chargeSessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeSession'
          links:
            getVehicleById:
              operationId: getVehicle
              parameters:
                vehicleId: '$response.body#/vehicleId'
  /proofs:
    get:
      operationId: getProofs
      parameters:
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageProof'
  /reports:
    get:
      operationId: getReport
      parameters:
        - name: start-date
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Date'
        - name: end-date
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Date'
      responses:
        200:
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
  /vehicles/{vehicleId}:
    get:
      operationId: getVehicle
      parameters:
        - name: vehicleId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'

components:
  schemas:
    ChargeSession:
      description: information about a charge session
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: The unique identifier of this charge session.
        startedAt:
          type: string
          format: date-time
          description: Date and time when the session was started.
        startKwh:
          type: number
          description: Meter reading when the session was started.
        endedAt:
          type: string
          format: date-time
          description: Date and time when the session was ended.
        endKwh:
          type: number
          description: Meter reading when the session was ended.
        totalKwh:
          type: number
          description: Total kWh charged in this session.
        odoMeter:
          type: integer
          minLength: 1
          description: The mileage of the vehicle during this session.
        type:
          $ref: '#/components/schemas/SessionType'
        vehicleId:
          type: string
          format: uuid
          readOnly: true
          description: The unique identifier of the vehicle bound to this session.
    Vehicle:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: The unique identifier of this vehicle.
        name:
          type: string
          minLength: 1
          maxLength: 40
          description: The name of this vehicle.
        odometer:
          type: integer
          description: The current mileage displayed by the odometer.
    ChargeSessionPage:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/ChargeSession'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        pageable:
          $ref: '#/components/schemas/Pageable'
        numberOfElements:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean
    Proof:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
    PageProof:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/Proof'
        number:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/Sort'
        pageable:
          $ref: '#/components/schemas/Pageable'
        numberOfElements:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        empty:
          type: boolean

    SessionType:
      description: >
        Session type:
         * `anonymous` - No vehicle found during this session
         * `registered` - Vehicle registered and its id is set to vehicleId
      type: string
      default: anonymous
      enum:
        - anonymous
        - registered

    Date:
      description: object representing a date as YYYY-MM-DD
      type: string
      format: date
      example: '2023-05-17'

    Pageable:
      description: minimal Pageable query parameters
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
          default: 0
        pageSize:
          type: integer
          format: int32
          default: 30
        paged:
          type: boolean
        unpaged:
          type: boolean
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        unsorted:
          type: boolean
        sorted:
          type: boolean